from git import Repo #pip install gitpython
import time
import shutil

# The scoreboard is an autogenerated HTML file located in the PC^2 working directory
# This function grabs that HTML file and moves it into our git repo as an index
def getScoreboard():
    source = 'html/full.html'
    dest = 'shakercodingclub.github.io/sciv/scoreboard/index.html'
    shutil.copyfile(source, dest)

# This adds and pushes the file
# The script is run from the repo's parent directory
def pushScoreboard():
    repo_dir = 'shakercodingclub.github.io'
    repo = Repo(repo_dir)
    file_list = ['sciv/scoreboard/index.html']
    commit_message = 'Test autoupload scoreboard refresh'
    repo.index.add(file_list)
    repo.index.commit(commit_message)
    origin = repo.remote('origin')
    origin.push()

while True:
    getScoreboard()
    print(time.ctime(), 'SUCCESSFUL MOVE')
    pushScoreboard()
    print(time.ctime(), 'SUCCESSFUL PUSH')
    time.sleep(60)
